config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  constraints CanAccessAdmin do
    namespace :admin do
      mount Flipper::UI.app(Flipper) => '/flipper', as: 'flipper'
    end
  end

  devise_for :users,
             path: 'user',
             path_names: { sign_in: 'login',
                           sign_out: 'logout',
                           sign_up: 'user' },
             controllers: { registrations: 'users/registrations' }

  constraints CanUserRegister do
    devise_scope :user do
      get '/user/registration' => 'users/registrations#new'
      post '/user/registration' => 'users/registrations#create'
      put '/user/registration' => 'users/registrations#update'
      patch '/user/registration' => 'users/registrations#update'
      delete '/user/registration' => 'users/registrations#destroy'
    end
  end

  authenticate :user do
    resources :campaigns do
      resources :campaign_invites, only: %i[index create]
    end
    resources :characters
  end

  get '*path' => redirect('/') unless Rails.env.development?

  root to: 'home#index'
end

app/models/character.rb
# == Schema Information
#
# Table name: characters
#
#  id                 :integer          not null, primary key
#  name               :string
#  character_race_id  :integer
#  character_class_id :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  user_id            :integer
#
# Indexes
#
#  index_characters_on_character_class_id  (character_class_id)
#  index_characters_on_character_race_id   (character_race_id)
#  index_characters_on_user_id             (user_id)
#

class Character < ApplicationRecord
  belongs_to :user
  belongs_to :character_race
  belongs_to :character_class
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]
  before_action :set_races, only: [:show, :edit, :new]
  before_action :set_classes, only: [:show, :edit, :new]

  # GET /characters
  def index
    @characters = current_user.characters()
  end

  # GET /characters/:id
  def show
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/:id/edit
  def edit
  end

  # POST /characters
  def create
    @character = Character.new(character_params)
    @character.user_id = current_user.id

    if @character.save
      redirect_to @character, notice: 'Character was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /characters/:id
  def update
    if @character.update(character_params)
      redirect_to @character, notice: 'Character was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /characters/:id
  def destroy
    @character.destroy
    redirect_to characters_url, notice: 'Character was successfully destroyed.'
  end

  private

  def character_params
    params.require(:character).permit(:name, :character_race_id, :character_class_id)
  end

  def set_character
    @character = Character.find(params[:id])
  end

  def set_races
    @races = CharacterRace.all.sort_by(&:name).map { |n| [n.name, n.id] }
  end

  def set_classes
    @classes = CharacterClass.all.sort_by(&:name).map { |n| [n.name, n.id] }
  end
end

app/views/characters/_form.html.erb
<div class="form">
  <%= form_with(model: character, disabled: disabled) do |f| %>
    <div class="field">
      <%= f.label :name, class: "label" %>
      <div class="control">
        <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "input", required: "true", disabled: disabled %>
      </div>
    </div>
    <div class="field">
      <%= f.label :character_race_id, class: "label", value: "Race" %>
      <div class="select is-fullwidth">
        <%= f.select :character_race_id, options_for_select(@races, character.character_race_id), {}, { disabled: disabled } %>
      </div>
    </div>
    <div class="field">
      <%= f.label :character_class_id, class: "label", value: "Class" %>
      <div class="select is-fullwidth">
        <%= f.select :character_class_id, options_for_select(@classes, character.character_class_id), {}, { disabled: disabled } %>
      </div>
    </div>
    <% unless disabled %>
      <div class="field">
        <div class="control">
          <%= f.button class: "button is-link is-fullwidth" %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/characters/edit.html.erb
<%= render partial: "shared/navbar" %>
<div class="container">
  <div class="columns is-vcentered">
    <nav class="breadcrumb column" aria-label="breadcrumbs">
      <ul>
        <li>
          <%= link_to("Home", root_path) %>
        </li>
        <li>
          <%= link_to("Characters", characters_path) %>
        </li>
        <li>
          <%= link_to(@character.name, character_path) %>
        </li>
        <li class="is-active">
          <a href="#">Edit</a>
        </li>
      </ul>
    </nav>
  </div>
  <div class="columns is-centered">
    <div class="column">
      <%= render "form", character: @character, disabled: false %>
    </div>
  </div>
</div>

app/views/characters/index.html.erb
<%= render partial: "shared/navbar" %>
<div class="container">
  <div class="columns is-mobile is-vcentered">
    <nav class="breadcrumb column is-three-fifths-mobile" aria-label="breadcrumbs">
      <ul>
        <li>
          <%= link_to("Home", root_path) %>
        </li>
        <li class="is-active">
          <%= link_to("Characters", characters_path) %>
        </li>
      </ul>
    </nav>
    <div class="buttons column is-two-fifths-mobile has-text-right">
      <%= link_to("Create Character", new_character_path, class: "button is-link") %>
    </div>
  </div>
  <% if @characters.exists? %>
    <div class="columns">
      <% @characters.each do |character| %>
        <div class="column is-full-mobile is-one-third-tablet is-one-quarter-desktop">
          <article class="message is-dark">
            <div class="message-header">
              <p><%= character.name %></p>
              <%= link_to("Delete", character_path(character.id), method: :delete, class: "delete", data: { confirm: "Are you sure?" }) %>
            </div>
            <div class="message-body">
              <p class="has-text-weight-bold">Race</p>
              <p><%= character.character_race().name %></p>
              <p class="has-text-weight-bold has-margin-top-2">Class</p>
              <p><%= character.character_class().name %></p>
            </div>
            <%= link_to(edit_character_path(character.id), class: "button is-link is-fullwidth") do %>
              <span class="icon is-small">
                <i class="fas fa-pencil-alt"></i>
              </span>
              <span>Edit</span>
            <% end %>
          </article>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/characters/new.html.erb
<%= render partial: "shared/navbar" %>
<div class="container">
  <div class="columns is-vcentered">
    <nav class="breadcrumb column" aria-label="breadcrumbs">
      <ul>
        <li>
          <%= link_to("Home", root_path) %>
        </li>
        <li>
          <%= link_to("Characters", characters_path) %>
        </li>
        <li class="is-active">
          <a href="#">New</a>
        </li>
      </ul>
    </nav>
  </div>
  <div class="columns is-centered">
    <div class="column">
      <%= render "form", character: @character, disabled: false %>
    </div>
  </div>
</div>

app/views/characters/show.html.erb
<%= render partial: "shared/navbar" %>
<div class="container">
  <div class="columns is-mobile is-vcentered">
    <nav class="breadcrumb column is-three-fifths-mobile" aria-label="breadcrumbs">
      <ul>
        <li>
          <%= link_to("Home", root_path) %>
        </li>
        <li>
          <%= link_to("Characters", characters_path) %>
        </li>
        <li class="is-active">
          <%= link_to(@character.name, character_path) %>
        </li>
      </ul>
    </nav>
    <div class="buttons column is-two-fifths-mobile has-text-right">
      <%= link_to("Edit Character", edit_character_path, class: "button is-link") %>
    </div>
  </div>
  <div class="columns is-centered">
    <div class="column">
      <%= render "form", character: @character, disabled: true %>
    </div>
  </div>
</div>