config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  constraints CanAccessAdmin do
    namespace :admin do
      mount Flipper::UI.app(Flipper) => '/flipper', as: 'flipper'
    end
  end

  devise_for :users,
             path: 'user',
             path_names: { sign_in: 'login',
                           sign_out: 'logout',
                           sign_up: 'user' },
             controllers: { registrations: 'users/registrations' }

  constraints CanUserRegister do
    devise_scope :user do
      get '/user/registration' => 'users/registrations#new'
      post '/user/registration' => 'users/registrations#create'
      put '/user/registration' => 'users/registrations#update'
      patch '/user/registration' => 'users/registrations#update'
      delete '/user/registration' => 'users/registrations#destroy'
    end
  end

  authenticate :user do
    resources :campaigns do
      resources :campaign_invites, only: %i[index create]
    end
    resources :characters
  end

  get '*path' => redirect('/') unless Rails.env.development?

  root to: 'home#index'
end

app/models/campaign.rb
# == Schema Information
#
# Table name: campaigns
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Campaign < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :campaign_invites, dependent: :delete_all
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]

  # GET /campaigns
  def index
    @campaigns = current_user.campaigns()
  end

  # GET /campaigns/:id
  def show
  end

  # GET /campaigns/new
  def new
    @campaign = Campaign.new
  end

  # GET /campaigns/:id/edit
  def edit
  end

  # POST /campaigns
  def create
    @campaign = Campaign.new(campaign_params)
    @campaign.users << current_user

    if @campaign.save
      redirect_to campaign_campaign_invites_path(@campaign), notice: 'Campaign was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /campaigns/:id
  def update
    if @campaign.update(campaign_params)
      redirect_to @campaign, notice: 'Campaign was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /campaigns/:id
  def destroy
    @campaign.destroy
    redirect_to campaigns_url, notice: 'Campaign was successfully destroyed.'
  end

  private

  def campaign_params
    params.require(:campaign).permit(:name, :description)
  end

  def set_campaign
    @campaign = Campaign.find(params[:id])
  end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_form.html.erb
<div class="form">
  <%= form_with(model: campaign, disabled: disabled) do |f| %>
    <div class="field">
      <%= f.label :name, class: "label" %>
      <div class="control">
        <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "input", required: "true", disabled: disabled %>
      </div>
    </div>
    <div class="field">
      <%= f.label :description, class: "label" %>
      <div class="control">
        <%= f.text_area :description, autocomplete: "description", class: "textarea", disabled: disabled %>
      </div>
    </div>
    <% unless disabled %>
      <div class="field">
        <div class="control">
          <%= f.button class: "button is-link is-fullwidth" %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/campaigns/edit.html.erb
<%= render partial: "shared/navbar" %>
<div class="container">
  <div class="columns is-vcentered">
    <nav class="breadcrumb column" aria-label="breadcrumbs">
      <ul>
        <li>
          <%= link_to("Home", root_path) %>
        </li>
        <li>
          <%= link_to("Campaigns", campaigns_path) %>
        </li>
        <li>
          <%= link_to(@campaign.name, campaign_path) %>
        </li>
        <li class="is-active">
          <a href="#">Edit</a>
        </li>
      </ul>
    </nav>
  </div>
  <div class="columns is-centered">
    <div class="column">
      <%= render "form", campaign: @campaign, disabled: false %>
    </div>
  </div>
</div>

app/views/campaigns/index.html.erb
<%= render partial: "shared/navbar" %>
<div class="container">
  <div class="columns is-mobile is-vcentered">
    <nav class="breadcrumb column is-three-fifths-mobile" aria-label="breadcrumbs">
      <ul>
        <li>
          <%= link_to("Home", root_path) %>
        </li>
        <li class="is-active">
          <%= link_to("Campaigns", campaigns_path) %>
        </li>
      </ul>
    </nav>
    <div class="buttons column is-two-fifths-mobile has-text-right">
      <%= link_to("Create Campaign", new_campaign_path, class: "button is-link") %>
    </div>
  </div>
  <% if @campaigns.exists? %>
    <div class="columns">
      <% @campaigns.each do |campaign| %>
        <div class="column is-full-mobile is-one-third-tablet is-one-quarter-desktop">
          <article class="message is-dark">
            <div class="message-header">
              <p><%= campaign.name %></p>
              <%= link_to("Delete", campaign_path(campaign.id), method: :delete, class: "delete", data: { confirm: "Are you sure?" }) %>
            </div>
            <div class="message-body">
              <p class="has-text-weight-bold">Description</p>
              <p><%= campaign.description %></p>
              <p class="has-text-weight-bold has-margin-top-2">Users</p>
              <% campaign.users().each do |campaign_user| %>
                <p><%= campaign_user.username %></p>
              <% end %>
            </div>
            <%= link_to(edit_campaign_path(campaign.id), class: "button is-link is-fullwidth") do %>
              <span class="icon is-small">
                <i class="fas fa-pencil-alt"></i>
              </span>
              <span>Edit</span>
            <% end %>
          </article>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/campaigns/new.html.erb
<%= render partial: "shared/navbar" %>
<div class="container">
  <div class="columns is-vcentered">
    <nav class="breadcrumb column" aria-label="breadcrumbs">
      <ul>
        <li>
          <%= link_to("Home", root_path) %>
        </li>
        <li>
          <%= link_to("Campaigns", campaigns_path) %>
        </li>
        <li class="is-active">
          <a href="#">New</a>
        </li>
      </ul>
    </nav>
  </div>
  <div class="columns is-centered">
    <div class="column">
      <%= render "form", campaign: @campaign, disabled: false %>
    </div>
  </div>
</div>

app/views/campaigns/show.html.erb
<%= render partial: "shared/navbar" %>
<div class="container">
  <div class="columns is-mobile is-vcentered">
    <nav class="breadcrumb column is-three-fifths-mobile" aria-label="breadcrumbs">
      <ul>
        <li>
          <%= link_to("Home", root_path) %>
        </li>
        <li>
          <%= link_to("Campaigns", campaigns_path) %>
        </li>
        <li class="is-active">
          <%= link_to(@campaign.name, campaign_path) %>
        </li>
      </ul>
    </nav>
    <div class="buttons column is-two-fifths-mobile has-text-right">
      <%= link_to("Edit Campaign", edit_campaign_path, class: "button is-link") %>
    </div>
  </div>
  <div class="columns is-centered">
    <div class="column">
      <%= render "form", campaign: @campaign, disabled: true %>
    </div>
  </div>
</div>